// Generated by CoffeeScript 1.6.3
(function() {
  var MDParser, parser;

  MDParser = require("./lib/index");

  parser = new MDParser;

  parser = new MDParser;

  parser.generateGrammar();

  parser.printGrammar();

}).call(this);
