// Generated by CoffeeScript 1.6.2
(function() {
  var MDParser, extending_md, parser;

  MDParser = require("./lib/index");

  parser = new MDParser;

  extending_md = "\nrule :: rule#[dash_rule | star_rule | eq_rule] space* eol+;\n\neq_rule :: eq_rulesub eq_rulesub eq_rulesub+ ;\neq_rulesub :: space* '=' ;\n";

  parser.loadFile("test.md", function() {
    var ret;

    this.extendGrammar(extending_md);
    return ret = this.parseMarkdown(function(md, success) {
      if (!success) {
        throw Error("error parsing markdown");
      }
      return console.log(JSON.stringify(md, null, 2));
    });
  });

}).call(this);
